apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-deploy
  namespace: hello
spec:
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
        - name: hello-server
          image: traefik/whoami:v1.10.4
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-nodeport
  namespace: hello
spec:
  type: NodePort
  # Preserve client source IP. With Local policy, each node must have a local endpoint.
  externalTrafficPolicy: Local
  selector:
    app: hello-server
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32080
