all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /tmp/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    frr_nodes:
      hosts:
        host_01:
          ansible_host: 172.232.217.185
          host_name: ap-vip-host-01
          node_role: primary
          vlan_ip: 172.16.1.11
          peer_vlan_ip: 172.16.1.12
          vlan_vip: 172.16.1.100
        host_02:
          ansible_host: 172.232.218.225
          host_name: ap-vip-host-02
          node_role: secondary
          vlan_ip: 172.16.1.12
          peer_vlan_ip: 172.16.1.11
          vlan_vip: 172.16.1.100
