apiVersion: v1
kind: Namespace
metadata:
  name: private
  labels:
    name: private
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-client
  namespace: private
  labels:
    app: pg-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-client
  template:
    metadata:
      labels:
        app: pg-client
    spec:
      containers:
        - name: pg-client
          image: postgres:16
          command: ["/bin/sh", "-c"]
          args:
            - sleep infinity
          readinessProbe:
            exec:
              command:
                [
                  "/bin/sh",
                  "-c",
                  "psql --version >/dev/null 2>&1 && openssl version >/dev/null 2>&1",
                ]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
