apiVersion: v1
kind: Service
metadata:
  name: dummy-nodebalancer
  annotations:
    # keep the nb after deleting the service
    service.beta.kubernetes.io/linode-loadbalancer-preserve: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nonexistent # This selector won't match anything
