apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: demo-orders
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 3
  config:
    min.insync.replicas: 2
    retention.ms: 604800000
    cleanup.policy: delete
