#cloud-config
ssh_pwauth: false

write_files:
  - path: /usr/local/bin/setup-nat-gateway.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -x
      exec > >(tee /var/log/nat-gateway-setup.log) 2>&1

      echo "Starting NAT Gateway setup..."

      # Enable IP forwarding
      echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/99-nat.conf
      sysctl -p /etc/sysctl.d/99-nat.conf

      # Wait for network interfaces
      sleep 10

      # Install iptables-persistent
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y iptables-persistent

      # Add NAT rules for both VPC and VLAN subnets
      iptables -t nat -A POSTROUTING -o eth0 -s ${linode_vpc_subnet.private.ipv4} -j MASQUERADE
      iptables -t nat -A POSTROUTING -o eth0 -s 192.168.100.0/24 -j MASQUERADE

      # Allow forwarding
      iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
      iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT
      iptables -A FORWARD -i eth0 -o eth2 -m state --state RELATED,ESTABLISHED -j ACCEPT
      iptables -A FORWARD -i eth2 -o eth0 -j ACCEPT

      # Save rules
      iptables-save > /etc/iptables/rules.v4

      echo "NAT Gateway setup complete!"
      iptables -t nat -L -n -v

runcmd:
  - /usr/local/bin/setup-nat-gateway.sh
