# Cluster 01 Outputs
output "cluster_01_id" {
  value       = linode_lke_cluster.cluster_01.id
  description = "LKE Cluster 01 ID"
}

output "cluster_01_label" {
  value       = linode_lke_cluster.cluster_01.label
  description = "LKE Cluster 01 label"
}

output "cluster_01_api_endpoint" {
  value       = linode_lke_cluster.cluster_01.api_endpoints[0]
  description = "LKE Cluster 01 API endpoint"
}

output "cluster_01_kubeconfig_path" {
  value       = local_file.kubeconfig_cluster_01.filename
  description = "Path to Cluster 01 kubeconfig file"
}

# Cluster 02 Outputs
output "cluster_02_id" {
  value       = linode_lke_cluster.cluster_02.id
  description = "LKE Cluster 02 ID"
}

output "cluster_02_label" {
  value       = linode_lke_cluster.cluster_02.label
  description = "LKE Cluster 02 label"
}

output "cluster_02_api_endpoint" {
  value       = linode_lke_cluster.cluster_02.api_endpoints[0]
  description = "LKE Cluster 02 API endpoint"
}

output "cluster_02_kubeconfig_path" {
  value       = local_file.kubeconfig_cluster_02.filename
  description = "Path to Cluster 02 kubeconfig file"
}

# Combined outputs for easy access
output "kubectl_cluster_01_command" {
  value       = "export KUBECONFIG=${local_file.kubeconfig_cluster_01.filename}"
  description = "Command to set kubectl context to Cluster 01"
}

output "kubectl_cluster_02_command" {
  value       = "export KUBECONFIG=${local_file.kubeconfig_cluster_02.filename}"
  description = "Command to set kubectl context to Cluster 02"
}

output "kubectl_both_clusters_command" {
  value       = "export KUBECONFIG=${local_file.kubeconfig_cluster_01.filename}:${local_file.kubeconfig_cluster_02.filename}"
  description = "Command to set kubectl context to both clusters"
}

# External PostgreSQL VM outputs
output "postgres_vm_label" {
  value       = linode_instance.postgres_vm.label
  description = "External PostgreSQL VM label"
}

output "postgres_vm_public_ip" {
  value       = tolist(linode_instance.postgres_vm.ipv4[*])[0]
  description = "External PostgreSQL VM public IPv4"
}

output "postgres_vm_private_ip" {
  value       = try(tolist(linode_instance.postgres_vm.ipv4[*])[1], "")
  description = "External PostgreSQL VM private IPv4 (if assigned)"
}

output "postgres_vm_endpoint" {
  value       = "${tolist(linode_instance.postgres_vm.ipv4[*])[0]}:${var.postgres_port}"
  description = "External PostgreSQL endpoint to be used by the Skupper connector"
}

output "postgres_db_name" {
  value       = var.postgres_db_name
  description = "Demo PostgreSQL database name"
}

output "postgres_db_user" {
  value       = var.postgres_db_user
  description = "Demo PostgreSQL username"
}

output "postgres_port" {
  value       = var.postgres_port
  description = "Demo PostgreSQL TCP port"
}

output "postgres_db_password" {
  value       = random_password.postgres_db_password.result
  description = "Demo PostgreSQL password"
  sensitive   = true
}

output "postgres_ca_cert_path" {
  value       = local_file.postgres_server_ca.filename
  description = "Path to self-signed PostgreSQL CA/server certificate for sslmode=verify-ca tests"
}

output "postgres_vm_ssh_private_key_path" {
  value       = local_file.postgres_private_key.filename
  description = "Local path to autogenerated SSH private key for PostgreSQL VM"
}

output "postgres_vm_ssh_public_key_path" {
  value       = local_file.postgres_public_key.filename
  description = "Local path to autogenerated SSH public key for PostgreSQL VM"
}

output "postgres_vm_direct_ssh_command" {
  value       = "ssh -i ${local_file.postgres_private_key.filename} -o IdentitiesOnly=yes root@${tolist(linode_instance.postgres_vm.ipv4[*])[0]}"
  description = "Direct SSH command to access PostgreSQL VM using autogenerated key"
}

output "postgres_vm_direct_cloud_init_logs_command" {
  value       = "ssh -i ${local_file.postgres_private_key.filename} -o IdentitiesOnly=yes root@${tolist(linode_instance.postgres_vm.ipv4[*])[0]} 'tail -f /var/log/cloud-init-output.log /var/log/cloud-init.log'"
  description = "Direct SSH command to tail cloud-init logs on PostgreSQL VM"
}

output "postgres_vm_direct_service_check_command" {
  value       = "ssh -i ${local_file.postgres_private_key.filename} -o IdentitiesOnly=yes root@${tolist(linode_instance.postgres_vm.ipv4[*])[0]} 'systemctl status postgresql --no-pager && ss -lntp | grep :${var.postgres_port}'"
  description = "Direct SSH command to verify PostgreSQL service status and listening port"
}

output "postgres_vm_manual_bootstrap_command" {
  value       = "ssh -i ${local_file.postgres_private_key.filename} -o IdentitiesOnly=yes root@${tolist(linode_instance.postgres_vm.ipv4[*])[0]} 'bash /usr/local/bin/bootstrap-postgres.sh && systemctl status postgresql --no-pager'"
  description = "Direct SSH command to rerun PostgreSQL bootstrap script manually"
}

output "postgres_vm_debug_recent_logs_command" {
  value       = "ssh -i ${local_file.postgres_private_key.filename} -o IdentitiesOnly=yes root@${tolist(linode_instance.postgres_vm.ipv4[*])[0]} 'echo \"=== /var/log/postgres-bootstrap.log (last 100) ===\"; tail -n 100 /var/log/postgres-bootstrap.log 2>/dev/null || echo \"bootstrap log not found\"; echo; echo \"=== journalctl -u postgresql (last 100) ===\"; journalctl -u postgresql --no-pager -n 100; echo; echo \"=== systemctl status postgresql ===\"; systemctl status postgresql --no-pager || true'"
  description = "Direct SSH command to show last 100 bootstrap and PostgreSQL journal lines"
}

output "postgres_vm_lish_ssh_command" {
  value       = "ssh -t ${data.linode_profile.me.username}@lish-${local.region}.linode.com ${linode_instance.postgres_vm.label}"
  description = "SSH command to access PostgreSQL VM through LISH"
}

output "postgres_vm_cloud_init_logs_command" {
  value       = "ssh -t ${data.linode_profile.me.username}@lish-${local.region}.linode.com ${linode_instance.postgres_vm.label} 'tail -f /var/log/cloud-init-output.log /var/log/cloud-init.log'"
  description = "Command to tail cloud-init logs on the PostgreSQL VM through LISH"
}

output "postgres_vm_service_check_command" {
  value       = "ssh -t ${data.linode_profile.me.username}@lish-${local.region}.linode.com ${linode_instance.postgres_vm.label} 'systemctl status postgresql --no-pager && ss -lntp | grep :${var.postgres_port}'"
  description = "Command to verify PostgreSQL service status and listening port on the VM"
}
