{
 "title": "NodeBalancer Details",
 "tags": [
  "linode",
  "nodebalancer"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "nodebalancer",
    "label": "NodeBalancer",
    "query": {
     "query": "label_values(linode_nodebalancer_transfer_total_mb, nodebalancer_label)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total NodeBalancers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "linode_nodebalancers_total" }
   ]
  },
  {
   "title": "Transfer In/Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "linode_nodebalancer_transfer_in_mb{nodebalancer_label=~\"$nodebalancer\"}",
     "legendFormat": "Inbound"
    },
    {
     "expr": "linode_nodebalancer_transfer_out_mb{nodebalancer_label=~\"$nodebalancer\"}",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Total Transfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "linode_nodebalancer_transfer_total_mb{nodebalancer_label=~\"$nodebalancer\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Client Connection Throttle",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "linode_nodebalancer_client_conn_throttle{nodebalancer_label=~\"$nodebalancer\"}",
     "legendFormat": "{{nodebalancer_label}}"
    }
   ]
  }
 ]
}